// Package restapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package restapi

// Hotel defines model for Hotel.
type Hotel struct {
	Address           string   `json:"address"`
	Amenities         []string `json:"amenities"`
	BookingConditions []string `json:"bookingConditions"`
	City              string   `json:"city"`
	Country           string   `json:"country"`
	Description       string   `json:"description"`
	DestinationId     int      `json:"destinationId"`
	Id                string   `json:"id"`
	Images            []Image  `json:"images"`
	Latitude          *float64 `json:"latitude,omitempty"`
	Longitude         *float64 `json:"longitude,omitempty"`
	Name              string   `json:"name"`
	PostalCode        string   `json:"postalCode"`
}

// Hotels defines model for Hotels.
type Hotels = []Hotel

// Image defines model for Image.
type Image struct {
	Category    string `json:"category"`
	Description string `json:"description"`
	Url         string `json:"url"`
}

// GetHotelsParams defines parameters for GetHotels.
type GetHotelsParams struct {
	Ids         *[]string `form:"ids,omitempty" json:"ids,omitempty"`
	Destination *int      `form:"destination,omitempty" json:"destination,omitempty"`
}
