// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DataColumns holds the columns for the "data" table.
	DataColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "destination_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "latitude", Type: field.TypeFloat64},
		{Name: "longitude", Type: field.TypeFloat64},
		{Name: "address", Type: field.TypeString},
		{Name: "city", Type: field.TypeString},
		{Name: "country", Type: field.TypeString},
		{Name: "details", Type: field.TypeString},
		{Name: "amenities", Type: field.TypeJSON},
		{Name: "images", Type: field.TypeJSON},
		{Name: "provider", Type: field.TypeString},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// DataTable holds the schema information for the "data" table.
	DataTable = &schema.Table{
		Name:       "data",
		Columns:    DataColumns,
		PrimaryKey: []*schema.Column{DataColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "data_id",
				Unique:  true,
				Columns: []*schema.Column{DataColumns[0]},
			},
		},
	}
	// HotelsColumns holds the columns for the "hotels" table.
	HotelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "destination_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "latitude", Type: field.TypeFloat64},
		{Name: "longitude", Type: field.TypeFloat64},
		{Name: "address", Type: field.TypeString},
		{Name: "city", Type: field.TypeString},
		{Name: "country", Type: field.TypeString},
		{Name: "details", Type: field.TypeString},
		{Name: "amenities", Type: field.TypeJSON},
		{Name: "images", Type: field.TypeJSON},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// HotelsTable holds the schema information for the "hotels" table.
	HotelsTable = &schema.Table{
		Name:       "hotels",
		Columns:    HotelsColumns,
		PrimaryKey: []*schema.Column{HotelsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "hotel_id",
				Unique:  true,
				Columns: []*schema.Column{HotelsColumns[0]},
			},
			{
				Name:    "hotel_destination_id",
				Unique:  false,
				Columns: []*schema.Column{HotelsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DataTable,
		HotelsTable,
	}
)

func init() {
}
