// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/choonhong/hotel-data-merge/domain"
	"github.com/choonhong/hotel-data-merge/ent/hotel"
	"github.com/choonhong/hotel-data-merge/ent/predicate"
)

// HotelUpdate is the builder for updating Hotel entities.
type HotelUpdate struct {
	config
	hooks    []Hook
	mutation *HotelMutation
}

// Where appends a list predicates to the HotelUpdate builder.
func (hu *HotelUpdate) Where(ps ...predicate.Hotel) *HotelUpdate {
	hu.mutation.Where(ps...)
	return hu
}

// SetDestinationID sets the "destination_id" field.
func (hu *HotelUpdate) SetDestinationID(s string) *HotelUpdate {
	hu.mutation.SetDestinationID(s)
	return hu
}

// SetNillableDestinationID sets the "destination_id" field if the given value is not nil.
func (hu *HotelUpdate) SetNillableDestinationID(s *string) *HotelUpdate {
	if s != nil {
		hu.SetDestinationID(*s)
	}
	return hu
}

// SetName sets the "name" field.
func (hu *HotelUpdate) SetName(s string) *HotelUpdate {
	hu.mutation.SetName(s)
	return hu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (hu *HotelUpdate) SetNillableName(s *string) *HotelUpdate {
	if s != nil {
		hu.SetName(*s)
	}
	return hu
}

// SetLatitude sets the "latitude" field.
func (hu *HotelUpdate) SetLatitude(f float64) *HotelUpdate {
	hu.mutation.ResetLatitude()
	hu.mutation.SetLatitude(f)
	return hu
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (hu *HotelUpdate) SetNillableLatitude(f *float64) *HotelUpdate {
	if f != nil {
		hu.SetLatitude(*f)
	}
	return hu
}

// AddLatitude adds f to the "latitude" field.
func (hu *HotelUpdate) AddLatitude(f float64) *HotelUpdate {
	hu.mutation.AddLatitude(f)
	return hu
}

// SetLongitude sets the "longitude" field.
func (hu *HotelUpdate) SetLongitude(f float64) *HotelUpdate {
	hu.mutation.ResetLongitude()
	hu.mutation.SetLongitude(f)
	return hu
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (hu *HotelUpdate) SetNillableLongitude(f *float64) *HotelUpdate {
	if f != nil {
		hu.SetLongitude(*f)
	}
	return hu
}

// AddLongitude adds f to the "longitude" field.
func (hu *HotelUpdate) AddLongitude(f float64) *HotelUpdate {
	hu.mutation.AddLongitude(f)
	return hu
}

// SetAddress sets the "address" field.
func (hu *HotelUpdate) SetAddress(s string) *HotelUpdate {
	hu.mutation.SetAddress(s)
	return hu
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (hu *HotelUpdate) SetNillableAddress(s *string) *HotelUpdate {
	if s != nil {
		hu.SetAddress(*s)
	}
	return hu
}

// SetCity sets the "city" field.
func (hu *HotelUpdate) SetCity(s string) *HotelUpdate {
	hu.mutation.SetCity(s)
	return hu
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (hu *HotelUpdate) SetNillableCity(s *string) *HotelUpdate {
	if s != nil {
		hu.SetCity(*s)
	}
	return hu
}

// SetCountry sets the "country" field.
func (hu *HotelUpdate) SetCountry(s string) *HotelUpdate {
	hu.mutation.SetCountry(s)
	return hu
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (hu *HotelUpdate) SetNillableCountry(s *string) *HotelUpdate {
	if s != nil {
		hu.SetCountry(*s)
	}
	return hu
}

// SetDetails sets the "details" field.
func (hu *HotelUpdate) SetDetails(s string) *HotelUpdate {
	hu.mutation.SetDetails(s)
	return hu
}

// SetNillableDetails sets the "details" field if the given value is not nil.
func (hu *HotelUpdate) SetNillableDetails(s *string) *HotelUpdate {
	if s != nil {
		hu.SetDetails(*s)
	}
	return hu
}

// SetAmenities sets the "amenities" field.
func (hu *HotelUpdate) SetAmenities(s []string) *HotelUpdate {
	hu.mutation.SetAmenities(s)
	return hu
}

// AppendAmenities appends s to the "amenities" field.
func (hu *HotelUpdate) AppendAmenities(s []string) *HotelUpdate {
	hu.mutation.AppendAmenities(s)
	return hu
}

// SetImages sets the "images" field.
func (hu *HotelUpdate) SetImages(d []domain.Image) *HotelUpdate {
	hu.mutation.SetImages(d)
	return hu
}

// AppendImages appends d to the "images" field.
func (hu *HotelUpdate) AppendImages(d []domain.Image) *HotelUpdate {
	hu.mutation.AppendImages(d)
	return hu
}

// SetUpdatedAt sets the "updated_at" field.
func (hu *HotelUpdate) SetUpdatedAt(t time.Time) *HotelUpdate {
	hu.mutation.SetUpdatedAt(t)
	return hu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (hu *HotelUpdate) SetNillableUpdatedAt(t *time.Time) *HotelUpdate {
	if t != nil {
		hu.SetUpdatedAt(*t)
	}
	return hu
}

// Mutation returns the HotelMutation object of the builder.
func (hu *HotelUpdate) Mutation() *HotelMutation {
	return hu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (hu *HotelUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, hu.sqlSave, hu.mutation, hu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (hu *HotelUpdate) SaveX(ctx context.Context) int {
	affected, err := hu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (hu *HotelUpdate) Exec(ctx context.Context) error {
	_, err := hu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hu *HotelUpdate) ExecX(ctx context.Context) {
	if err := hu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (hu *HotelUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(hotel.Table, hotel.Columns, sqlgraph.NewFieldSpec(hotel.FieldID, field.TypeString))
	if ps := hu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := hu.mutation.DestinationID(); ok {
		_spec.SetField(hotel.FieldDestinationID, field.TypeString, value)
	}
	if value, ok := hu.mutation.Name(); ok {
		_spec.SetField(hotel.FieldName, field.TypeString, value)
	}
	if value, ok := hu.mutation.Latitude(); ok {
		_spec.SetField(hotel.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := hu.mutation.AddedLatitude(); ok {
		_spec.AddField(hotel.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := hu.mutation.Longitude(); ok {
		_spec.SetField(hotel.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := hu.mutation.AddedLongitude(); ok {
		_spec.AddField(hotel.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := hu.mutation.Address(); ok {
		_spec.SetField(hotel.FieldAddress, field.TypeString, value)
	}
	if value, ok := hu.mutation.City(); ok {
		_spec.SetField(hotel.FieldCity, field.TypeString, value)
	}
	if value, ok := hu.mutation.Country(); ok {
		_spec.SetField(hotel.FieldCountry, field.TypeString, value)
	}
	if value, ok := hu.mutation.Details(); ok {
		_spec.SetField(hotel.FieldDetails, field.TypeString, value)
	}
	if value, ok := hu.mutation.Amenities(); ok {
		_spec.SetField(hotel.FieldAmenities, field.TypeJSON, value)
	}
	if value, ok := hu.mutation.AppendedAmenities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, hotel.FieldAmenities, value)
		})
	}
	if value, ok := hu.mutation.Images(); ok {
		_spec.SetField(hotel.FieldImages, field.TypeJSON, value)
	}
	if value, ok := hu.mutation.AppendedImages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, hotel.FieldImages, value)
		})
	}
	if value, ok := hu.mutation.UpdatedAt(); ok {
		_spec.SetField(hotel.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, hu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hotel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	hu.mutation.done = true
	return n, nil
}

// HotelUpdateOne is the builder for updating a single Hotel entity.
type HotelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HotelMutation
}

// SetDestinationID sets the "destination_id" field.
func (huo *HotelUpdateOne) SetDestinationID(s string) *HotelUpdateOne {
	huo.mutation.SetDestinationID(s)
	return huo
}

// SetNillableDestinationID sets the "destination_id" field if the given value is not nil.
func (huo *HotelUpdateOne) SetNillableDestinationID(s *string) *HotelUpdateOne {
	if s != nil {
		huo.SetDestinationID(*s)
	}
	return huo
}

// SetName sets the "name" field.
func (huo *HotelUpdateOne) SetName(s string) *HotelUpdateOne {
	huo.mutation.SetName(s)
	return huo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (huo *HotelUpdateOne) SetNillableName(s *string) *HotelUpdateOne {
	if s != nil {
		huo.SetName(*s)
	}
	return huo
}

// SetLatitude sets the "latitude" field.
func (huo *HotelUpdateOne) SetLatitude(f float64) *HotelUpdateOne {
	huo.mutation.ResetLatitude()
	huo.mutation.SetLatitude(f)
	return huo
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (huo *HotelUpdateOne) SetNillableLatitude(f *float64) *HotelUpdateOne {
	if f != nil {
		huo.SetLatitude(*f)
	}
	return huo
}

// AddLatitude adds f to the "latitude" field.
func (huo *HotelUpdateOne) AddLatitude(f float64) *HotelUpdateOne {
	huo.mutation.AddLatitude(f)
	return huo
}

// SetLongitude sets the "longitude" field.
func (huo *HotelUpdateOne) SetLongitude(f float64) *HotelUpdateOne {
	huo.mutation.ResetLongitude()
	huo.mutation.SetLongitude(f)
	return huo
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (huo *HotelUpdateOne) SetNillableLongitude(f *float64) *HotelUpdateOne {
	if f != nil {
		huo.SetLongitude(*f)
	}
	return huo
}

// AddLongitude adds f to the "longitude" field.
func (huo *HotelUpdateOne) AddLongitude(f float64) *HotelUpdateOne {
	huo.mutation.AddLongitude(f)
	return huo
}

// SetAddress sets the "address" field.
func (huo *HotelUpdateOne) SetAddress(s string) *HotelUpdateOne {
	huo.mutation.SetAddress(s)
	return huo
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (huo *HotelUpdateOne) SetNillableAddress(s *string) *HotelUpdateOne {
	if s != nil {
		huo.SetAddress(*s)
	}
	return huo
}

// SetCity sets the "city" field.
func (huo *HotelUpdateOne) SetCity(s string) *HotelUpdateOne {
	huo.mutation.SetCity(s)
	return huo
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (huo *HotelUpdateOne) SetNillableCity(s *string) *HotelUpdateOne {
	if s != nil {
		huo.SetCity(*s)
	}
	return huo
}

// SetCountry sets the "country" field.
func (huo *HotelUpdateOne) SetCountry(s string) *HotelUpdateOne {
	huo.mutation.SetCountry(s)
	return huo
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (huo *HotelUpdateOne) SetNillableCountry(s *string) *HotelUpdateOne {
	if s != nil {
		huo.SetCountry(*s)
	}
	return huo
}

// SetDetails sets the "details" field.
func (huo *HotelUpdateOne) SetDetails(s string) *HotelUpdateOne {
	huo.mutation.SetDetails(s)
	return huo
}

// SetNillableDetails sets the "details" field if the given value is not nil.
func (huo *HotelUpdateOne) SetNillableDetails(s *string) *HotelUpdateOne {
	if s != nil {
		huo.SetDetails(*s)
	}
	return huo
}

// SetAmenities sets the "amenities" field.
func (huo *HotelUpdateOne) SetAmenities(s []string) *HotelUpdateOne {
	huo.mutation.SetAmenities(s)
	return huo
}

// AppendAmenities appends s to the "amenities" field.
func (huo *HotelUpdateOne) AppendAmenities(s []string) *HotelUpdateOne {
	huo.mutation.AppendAmenities(s)
	return huo
}

// SetImages sets the "images" field.
func (huo *HotelUpdateOne) SetImages(d []domain.Image) *HotelUpdateOne {
	huo.mutation.SetImages(d)
	return huo
}

// AppendImages appends d to the "images" field.
func (huo *HotelUpdateOne) AppendImages(d []domain.Image) *HotelUpdateOne {
	huo.mutation.AppendImages(d)
	return huo
}

// SetUpdatedAt sets the "updated_at" field.
func (huo *HotelUpdateOne) SetUpdatedAt(t time.Time) *HotelUpdateOne {
	huo.mutation.SetUpdatedAt(t)
	return huo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (huo *HotelUpdateOne) SetNillableUpdatedAt(t *time.Time) *HotelUpdateOne {
	if t != nil {
		huo.SetUpdatedAt(*t)
	}
	return huo
}

// Mutation returns the HotelMutation object of the builder.
func (huo *HotelUpdateOne) Mutation() *HotelMutation {
	return huo.mutation
}

// Where appends a list predicates to the HotelUpdate builder.
func (huo *HotelUpdateOne) Where(ps ...predicate.Hotel) *HotelUpdateOne {
	huo.mutation.Where(ps...)
	return huo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (huo *HotelUpdateOne) Select(field string, fields ...string) *HotelUpdateOne {
	huo.fields = append([]string{field}, fields...)
	return huo
}

// Save executes the query and returns the updated Hotel entity.
func (huo *HotelUpdateOne) Save(ctx context.Context) (*Hotel, error) {
	return withHooks(ctx, huo.sqlSave, huo.mutation, huo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (huo *HotelUpdateOne) SaveX(ctx context.Context) *Hotel {
	node, err := huo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (huo *HotelUpdateOne) Exec(ctx context.Context) error {
	_, err := huo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (huo *HotelUpdateOne) ExecX(ctx context.Context) {
	if err := huo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (huo *HotelUpdateOne) sqlSave(ctx context.Context) (_node *Hotel, err error) {
	_spec := sqlgraph.NewUpdateSpec(hotel.Table, hotel.Columns, sqlgraph.NewFieldSpec(hotel.FieldID, field.TypeString))
	id, ok := huo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Hotel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := huo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hotel.FieldID)
		for _, f := range fields {
			if !hotel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != hotel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := huo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := huo.mutation.DestinationID(); ok {
		_spec.SetField(hotel.FieldDestinationID, field.TypeString, value)
	}
	if value, ok := huo.mutation.Name(); ok {
		_spec.SetField(hotel.FieldName, field.TypeString, value)
	}
	if value, ok := huo.mutation.Latitude(); ok {
		_spec.SetField(hotel.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := huo.mutation.AddedLatitude(); ok {
		_spec.AddField(hotel.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := huo.mutation.Longitude(); ok {
		_spec.SetField(hotel.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := huo.mutation.AddedLongitude(); ok {
		_spec.AddField(hotel.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := huo.mutation.Address(); ok {
		_spec.SetField(hotel.FieldAddress, field.TypeString, value)
	}
	if value, ok := huo.mutation.City(); ok {
		_spec.SetField(hotel.FieldCity, field.TypeString, value)
	}
	if value, ok := huo.mutation.Country(); ok {
		_spec.SetField(hotel.FieldCountry, field.TypeString, value)
	}
	if value, ok := huo.mutation.Details(); ok {
		_spec.SetField(hotel.FieldDetails, field.TypeString, value)
	}
	if value, ok := huo.mutation.Amenities(); ok {
		_spec.SetField(hotel.FieldAmenities, field.TypeJSON, value)
	}
	if value, ok := huo.mutation.AppendedAmenities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, hotel.FieldAmenities, value)
		})
	}
	if value, ok := huo.mutation.Images(); ok {
		_spec.SetField(hotel.FieldImages, field.TypeJSON, value)
	}
	if value, ok := huo.mutation.AppendedImages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, hotel.FieldImages, value)
		})
	}
	if value, ok := huo.mutation.UpdatedAt(); ok {
		_spec.SetField(hotel.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Hotel{config: huo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, huo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hotel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	huo.mutation.done = true
	return _node, nil
}
