// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/choonhong/hotel-data-merge/ent/hotel"
	"github.com/choonhong/hotel-data-merge/ent/predicate"
	"github.com/choonhong/hotel-data-merge/ent/schema"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeHotel = "Hotel"
)

// HotelMutation represents an operation that mutates the Hotel nodes in the graph.
type HotelMutation struct {
	config
	op                       Op
	typ                      string
	id                       *string
	destination_id           *int
	adddestination_id        *int
	name                     *string
	latitude                 *float64
	addlatitude              *float64
	longitude                *float64
	addlongitude             *float64
	address                  *string
	city                     *string
	country                  *string
	postal_code              *string
	description              *string
	amenities                *[]string
	appendamenities          []string
	images                   *[]schema.Image
	appendimages             []schema.Image
	booking_conditions       *[]string
	appendbooking_conditions []string
	updated_at               *time.Time
	clearedFields            map[string]struct{}
	done                     bool
	oldValue                 func(context.Context) (*Hotel, error)
	predicates               []predicate.Hotel
}

var _ ent.Mutation = (*HotelMutation)(nil)

// hotelOption allows management of the mutation configuration using functional options.
type hotelOption func(*HotelMutation)

// newHotelMutation creates new mutation for the Hotel entity.
func newHotelMutation(c config, op Op, opts ...hotelOption) *HotelMutation {
	m := &HotelMutation{
		config:        c,
		op:            op,
		typ:           TypeHotel,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withHotelID sets the ID field of the mutation.
func withHotelID(id string) hotelOption {
	return func(m *HotelMutation) {
		var (
			err   error
			once  sync.Once
			value *Hotel
		)
		m.oldValue = func(ctx context.Context) (*Hotel, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Hotel.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withHotel sets the old Hotel of the mutation.
func withHotel(node *Hotel) hotelOption {
	return func(m *HotelMutation) {
		m.oldValue = func(context.Context) (*Hotel, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m HotelMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m HotelMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Hotel entities.
func (m *HotelMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *HotelMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *HotelMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Hotel.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetDestinationID sets the "destination_id" field.
func (m *HotelMutation) SetDestinationID(i int) {
	m.destination_id = &i
	m.adddestination_id = nil
}

// DestinationID returns the value of the "destination_id" field in the mutation.
func (m *HotelMutation) DestinationID() (r int, exists bool) {
	v := m.destination_id
	if v == nil {
		return
	}
	return *v, true
}

// OldDestinationID returns the old "destination_id" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldDestinationID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDestinationID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDestinationID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDestinationID: %w", err)
	}
	return oldValue.DestinationID, nil
}

// AddDestinationID adds i to the "destination_id" field.
func (m *HotelMutation) AddDestinationID(i int) {
	if m.adddestination_id != nil {
		*m.adddestination_id += i
	} else {
		m.adddestination_id = &i
	}
}

// AddedDestinationID returns the value that was added to the "destination_id" field in this mutation.
func (m *HotelMutation) AddedDestinationID() (r int, exists bool) {
	v := m.adddestination_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetDestinationID resets all changes to the "destination_id" field.
func (m *HotelMutation) ResetDestinationID() {
	m.destination_id = nil
	m.adddestination_id = nil
}

// SetName sets the "name" field.
func (m *HotelMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *HotelMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *HotelMutation) ResetName() {
	m.name = nil
}

// SetLatitude sets the "latitude" field.
func (m *HotelMutation) SetLatitude(f float64) {
	m.latitude = &f
	m.addlatitude = nil
}

// Latitude returns the value of the "latitude" field in the mutation.
func (m *HotelMutation) Latitude() (r float64, exists bool) {
	v := m.latitude
	if v == nil {
		return
	}
	return *v, true
}

// OldLatitude returns the old "latitude" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldLatitude(ctx context.Context) (v *float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLatitude is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLatitude requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLatitude: %w", err)
	}
	return oldValue.Latitude, nil
}

// AddLatitude adds f to the "latitude" field.
func (m *HotelMutation) AddLatitude(f float64) {
	if m.addlatitude != nil {
		*m.addlatitude += f
	} else {
		m.addlatitude = &f
	}
}

// AddedLatitude returns the value that was added to the "latitude" field in this mutation.
func (m *HotelMutation) AddedLatitude() (r float64, exists bool) {
	v := m.addlatitude
	if v == nil {
		return
	}
	return *v, true
}

// ClearLatitude clears the value of the "latitude" field.
func (m *HotelMutation) ClearLatitude() {
	m.latitude = nil
	m.addlatitude = nil
	m.clearedFields[hotel.FieldLatitude] = struct{}{}
}

// LatitudeCleared returns if the "latitude" field was cleared in this mutation.
func (m *HotelMutation) LatitudeCleared() bool {
	_, ok := m.clearedFields[hotel.FieldLatitude]
	return ok
}

// ResetLatitude resets all changes to the "latitude" field.
func (m *HotelMutation) ResetLatitude() {
	m.latitude = nil
	m.addlatitude = nil
	delete(m.clearedFields, hotel.FieldLatitude)
}

// SetLongitude sets the "longitude" field.
func (m *HotelMutation) SetLongitude(f float64) {
	m.longitude = &f
	m.addlongitude = nil
}

// Longitude returns the value of the "longitude" field in the mutation.
func (m *HotelMutation) Longitude() (r float64, exists bool) {
	v := m.longitude
	if v == nil {
		return
	}
	return *v, true
}

// OldLongitude returns the old "longitude" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldLongitude(ctx context.Context) (v *float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLongitude is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLongitude requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLongitude: %w", err)
	}
	return oldValue.Longitude, nil
}

// AddLongitude adds f to the "longitude" field.
func (m *HotelMutation) AddLongitude(f float64) {
	if m.addlongitude != nil {
		*m.addlongitude += f
	} else {
		m.addlongitude = &f
	}
}

// AddedLongitude returns the value that was added to the "longitude" field in this mutation.
func (m *HotelMutation) AddedLongitude() (r float64, exists bool) {
	v := m.addlongitude
	if v == nil {
		return
	}
	return *v, true
}

// ClearLongitude clears the value of the "longitude" field.
func (m *HotelMutation) ClearLongitude() {
	m.longitude = nil
	m.addlongitude = nil
	m.clearedFields[hotel.FieldLongitude] = struct{}{}
}

// LongitudeCleared returns if the "longitude" field was cleared in this mutation.
func (m *HotelMutation) LongitudeCleared() bool {
	_, ok := m.clearedFields[hotel.FieldLongitude]
	return ok
}

// ResetLongitude resets all changes to the "longitude" field.
func (m *HotelMutation) ResetLongitude() {
	m.longitude = nil
	m.addlongitude = nil
	delete(m.clearedFields, hotel.FieldLongitude)
}

// SetAddress sets the "address" field.
func (m *HotelMutation) SetAddress(s string) {
	m.address = &s
}

// Address returns the value of the "address" field in the mutation.
func (m *HotelMutation) Address() (r string, exists bool) {
	v := m.address
	if v == nil {
		return
	}
	return *v, true
}

// OldAddress returns the old "address" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldAddress(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAddress is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAddress requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAddress: %w", err)
	}
	return oldValue.Address, nil
}

// ResetAddress resets all changes to the "address" field.
func (m *HotelMutation) ResetAddress() {
	m.address = nil
}

// SetCity sets the "city" field.
func (m *HotelMutation) SetCity(s string) {
	m.city = &s
}

// City returns the value of the "city" field in the mutation.
func (m *HotelMutation) City() (r string, exists bool) {
	v := m.city
	if v == nil {
		return
	}
	return *v, true
}

// OldCity returns the old "city" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldCity(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCity is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCity requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCity: %w", err)
	}
	return oldValue.City, nil
}

// ClearCity clears the value of the "city" field.
func (m *HotelMutation) ClearCity() {
	m.city = nil
	m.clearedFields[hotel.FieldCity] = struct{}{}
}

// CityCleared returns if the "city" field was cleared in this mutation.
func (m *HotelMutation) CityCleared() bool {
	_, ok := m.clearedFields[hotel.FieldCity]
	return ok
}

// ResetCity resets all changes to the "city" field.
func (m *HotelMutation) ResetCity() {
	m.city = nil
	delete(m.clearedFields, hotel.FieldCity)
}

// SetCountry sets the "country" field.
func (m *HotelMutation) SetCountry(s string) {
	m.country = &s
}

// Country returns the value of the "country" field in the mutation.
func (m *HotelMutation) Country() (r string, exists bool) {
	v := m.country
	if v == nil {
		return
	}
	return *v, true
}

// OldCountry returns the old "country" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldCountry(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCountry is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCountry requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCountry: %w", err)
	}
	return oldValue.Country, nil
}

// ClearCountry clears the value of the "country" field.
func (m *HotelMutation) ClearCountry() {
	m.country = nil
	m.clearedFields[hotel.FieldCountry] = struct{}{}
}

// CountryCleared returns if the "country" field was cleared in this mutation.
func (m *HotelMutation) CountryCleared() bool {
	_, ok := m.clearedFields[hotel.FieldCountry]
	return ok
}

// ResetCountry resets all changes to the "country" field.
func (m *HotelMutation) ResetCountry() {
	m.country = nil
	delete(m.clearedFields, hotel.FieldCountry)
}

// SetPostalCode sets the "postal_code" field.
func (m *HotelMutation) SetPostalCode(s string) {
	m.postal_code = &s
}

// PostalCode returns the value of the "postal_code" field in the mutation.
func (m *HotelMutation) PostalCode() (r string, exists bool) {
	v := m.postal_code
	if v == nil {
		return
	}
	return *v, true
}

// OldPostalCode returns the old "postal_code" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldPostalCode(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPostalCode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPostalCode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPostalCode: %w", err)
	}
	return oldValue.PostalCode, nil
}

// ClearPostalCode clears the value of the "postal_code" field.
func (m *HotelMutation) ClearPostalCode() {
	m.postal_code = nil
	m.clearedFields[hotel.FieldPostalCode] = struct{}{}
}

// PostalCodeCleared returns if the "postal_code" field was cleared in this mutation.
func (m *HotelMutation) PostalCodeCleared() bool {
	_, ok := m.clearedFields[hotel.FieldPostalCode]
	return ok
}

// ResetPostalCode resets all changes to the "postal_code" field.
func (m *HotelMutation) ResetPostalCode() {
	m.postal_code = nil
	delete(m.clearedFields, hotel.FieldPostalCode)
}

// SetDescription sets the "description" field.
func (m *HotelMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *HotelMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ClearDescription clears the value of the "description" field.
func (m *HotelMutation) ClearDescription() {
	m.description = nil
	m.clearedFields[hotel.FieldDescription] = struct{}{}
}

// DescriptionCleared returns if the "description" field was cleared in this mutation.
func (m *HotelMutation) DescriptionCleared() bool {
	_, ok := m.clearedFields[hotel.FieldDescription]
	return ok
}

// ResetDescription resets all changes to the "description" field.
func (m *HotelMutation) ResetDescription() {
	m.description = nil
	delete(m.clearedFields, hotel.FieldDescription)
}

// SetAmenities sets the "amenities" field.
func (m *HotelMutation) SetAmenities(s []string) {
	m.amenities = &s
	m.appendamenities = nil
}

// Amenities returns the value of the "amenities" field in the mutation.
func (m *HotelMutation) Amenities() (r []string, exists bool) {
	v := m.amenities
	if v == nil {
		return
	}
	return *v, true
}

// OldAmenities returns the old "amenities" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldAmenities(ctx context.Context) (v []string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAmenities is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAmenities requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAmenities: %w", err)
	}
	return oldValue.Amenities, nil
}

// AppendAmenities adds s to the "amenities" field.
func (m *HotelMutation) AppendAmenities(s []string) {
	m.appendamenities = append(m.appendamenities, s...)
}

// AppendedAmenities returns the list of values that were appended to the "amenities" field in this mutation.
func (m *HotelMutation) AppendedAmenities() ([]string, bool) {
	if len(m.appendamenities) == 0 {
		return nil, false
	}
	return m.appendamenities, true
}

// ClearAmenities clears the value of the "amenities" field.
func (m *HotelMutation) ClearAmenities() {
	m.amenities = nil
	m.appendamenities = nil
	m.clearedFields[hotel.FieldAmenities] = struct{}{}
}

// AmenitiesCleared returns if the "amenities" field was cleared in this mutation.
func (m *HotelMutation) AmenitiesCleared() bool {
	_, ok := m.clearedFields[hotel.FieldAmenities]
	return ok
}

// ResetAmenities resets all changes to the "amenities" field.
func (m *HotelMutation) ResetAmenities() {
	m.amenities = nil
	m.appendamenities = nil
	delete(m.clearedFields, hotel.FieldAmenities)
}

// SetImages sets the "images" field.
func (m *HotelMutation) SetImages(s []schema.Image) {
	m.images = &s
	m.appendimages = nil
}

// Images returns the value of the "images" field in the mutation.
func (m *HotelMutation) Images() (r []schema.Image, exists bool) {
	v := m.images
	if v == nil {
		return
	}
	return *v, true
}

// OldImages returns the old "images" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldImages(ctx context.Context) (v []schema.Image, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldImages is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldImages requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldImages: %w", err)
	}
	return oldValue.Images, nil
}

// AppendImages adds s to the "images" field.
func (m *HotelMutation) AppendImages(s []schema.Image) {
	m.appendimages = append(m.appendimages, s...)
}

// AppendedImages returns the list of values that were appended to the "images" field in this mutation.
func (m *HotelMutation) AppendedImages() ([]schema.Image, bool) {
	if len(m.appendimages) == 0 {
		return nil, false
	}
	return m.appendimages, true
}

// ClearImages clears the value of the "images" field.
func (m *HotelMutation) ClearImages() {
	m.images = nil
	m.appendimages = nil
	m.clearedFields[hotel.FieldImages] = struct{}{}
}

// ImagesCleared returns if the "images" field was cleared in this mutation.
func (m *HotelMutation) ImagesCleared() bool {
	_, ok := m.clearedFields[hotel.FieldImages]
	return ok
}

// ResetImages resets all changes to the "images" field.
func (m *HotelMutation) ResetImages() {
	m.images = nil
	m.appendimages = nil
	delete(m.clearedFields, hotel.FieldImages)
}

// SetBookingConditions sets the "booking_conditions" field.
func (m *HotelMutation) SetBookingConditions(s []string) {
	m.booking_conditions = &s
	m.appendbooking_conditions = nil
}

// BookingConditions returns the value of the "booking_conditions" field in the mutation.
func (m *HotelMutation) BookingConditions() (r []string, exists bool) {
	v := m.booking_conditions
	if v == nil {
		return
	}
	return *v, true
}

// OldBookingConditions returns the old "booking_conditions" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldBookingConditions(ctx context.Context) (v []string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBookingConditions is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBookingConditions requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBookingConditions: %w", err)
	}
	return oldValue.BookingConditions, nil
}

// AppendBookingConditions adds s to the "booking_conditions" field.
func (m *HotelMutation) AppendBookingConditions(s []string) {
	m.appendbooking_conditions = append(m.appendbooking_conditions, s...)
}

// AppendedBookingConditions returns the list of values that were appended to the "booking_conditions" field in this mutation.
func (m *HotelMutation) AppendedBookingConditions() ([]string, bool) {
	if len(m.appendbooking_conditions) == 0 {
		return nil, false
	}
	return m.appendbooking_conditions, true
}

// ClearBookingConditions clears the value of the "booking_conditions" field.
func (m *HotelMutation) ClearBookingConditions() {
	m.booking_conditions = nil
	m.appendbooking_conditions = nil
	m.clearedFields[hotel.FieldBookingConditions] = struct{}{}
}

// BookingConditionsCleared returns if the "booking_conditions" field was cleared in this mutation.
func (m *HotelMutation) BookingConditionsCleared() bool {
	_, ok := m.clearedFields[hotel.FieldBookingConditions]
	return ok
}

// ResetBookingConditions resets all changes to the "booking_conditions" field.
func (m *HotelMutation) ResetBookingConditions() {
	m.booking_conditions = nil
	m.appendbooking_conditions = nil
	delete(m.clearedFields, hotel.FieldBookingConditions)
}

// SetUpdatedAt sets the "updated_at" field.
func (m *HotelMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *HotelMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *HotelMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the HotelMutation builder.
func (m *HotelMutation) Where(ps ...predicate.Hotel) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the HotelMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *HotelMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Hotel, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *HotelMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *HotelMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Hotel).
func (m *HotelMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *HotelMutation) Fields() []string {
	fields := make([]string, 0, 13)
	if m.destination_id != nil {
		fields = append(fields, hotel.FieldDestinationID)
	}
	if m.name != nil {
		fields = append(fields, hotel.FieldName)
	}
	if m.latitude != nil {
		fields = append(fields, hotel.FieldLatitude)
	}
	if m.longitude != nil {
		fields = append(fields, hotel.FieldLongitude)
	}
	if m.address != nil {
		fields = append(fields, hotel.FieldAddress)
	}
	if m.city != nil {
		fields = append(fields, hotel.FieldCity)
	}
	if m.country != nil {
		fields = append(fields, hotel.FieldCountry)
	}
	if m.postal_code != nil {
		fields = append(fields, hotel.FieldPostalCode)
	}
	if m.description != nil {
		fields = append(fields, hotel.FieldDescription)
	}
	if m.amenities != nil {
		fields = append(fields, hotel.FieldAmenities)
	}
	if m.images != nil {
		fields = append(fields, hotel.FieldImages)
	}
	if m.booking_conditions != nil {
		fields = append(fields, hotel.FieldBookingConditions)
	}
	if m.updated_at != nil {
		fields = append(fields, hotel.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *HotelMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case hotel.FieldDestinationID:
		return m.DestinationID()
	case hotel.FieldName:
		return m.Name()
	case hotel.FieldLatitude:
		return m.Latitude()
	case hotel.FieldLongitude:
		return m.Longitude()
	case hotel.FieldAddress:
		return m.Address()
	case hotel.FieldCity:
		return m.City()
	case hotel.FieldCountry:
		return m.Country()
	case hotel.FieldPostalCode:
		return m.PostalCode()
	case hotel.FieldDescription:
		return m.Description()
	case hotel.FieldAmenities:
		return m.Amenities()
	case hotel.FieldImages:
		return m.Images()
	case hotel.FieldBookingConditions:
		return m.BookingConditions()
	case hotel.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *HotelMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case hotel.FieldDestinationID:
		return m.OldDestinationID(ctx)
	case hotel.FieldName:
		return m.OldName(ctx)
	case hotel.FieldLatitude:
		return m.OldLatitude(ctx)
	case hotel.FieldLongitude:
		return m.OldLongitude(ctx)
	case hotel.FieldAddress:
		return m.OldAddress(ctx)
	case hotel.FieldCity:
		return m.OldCity(ctx)
	case hotel.FieldCountry:
		return m.OldCountry(ctx)
	case hotel.FieldPostalCode:
		return m.OldPostalCode(ctx)
	case hotel.FieldDescription:
		return m.OldDescription(ctx)
	case hotel.FieldAmenities:
		return m.OldAmenities(ctx)
	case hotel.FieldImages:
		return m.OldImages(ctx)
	case hotel.FieldBookingConditions:
		return m.OldBookingConditions(ctx)
	case hotel.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Hotel field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *HotelMutation) SetField(name string, value ent.Value) error {
	switch name {
	case hotel.FieldDestinationID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDestinationID(v)
		return nil
	case hotel.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case hotel.FieldLatitude:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLatitude(v)
		return nil
	case hotel.FieldLongitude:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLongitude(v)
		return nil
	case hotel.FieldAddress:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAddress(v)
		return nil
	case hotel.FieldCity:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCity(v)
		return nil
	case hotel.FieldCountry:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCountry(v)
		return nil
	case hotel.FieldPostalCode:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPostalCode(v)
		return nil
	case hotel.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case hotel.FieldAmenities:
		v, ok := value.([]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAmenities(v)
		return nil
	case hotel.FieldImages:
		v, ok := value.([]schema.Image)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetImages(v)
		return nil
	case hotel.FieldBookingConditions:
		v, ok := value.([]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBookingConditions(v)
		return nil
	case hotel.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Hotel field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *HotelMutation) AddedFields() []string {
	var fields []string
	if m.adddestination_id != nil {
		fields = append(fields, hotel.FieldDestinationID)
	}
	if m.addlatitude != nil {
		fields = append(fields, hotel.FieldLatitude)
	}
	if m.addlongitude != nil {
		fields = append(fields, hotel.FieldLongitude)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *HotelMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case hotel.FieldDestinationID:
		return m.AddedDestinationID()
	case hotel.FieldLatitude:
		return m.AddedLatitude()
	case hotel.FieldLongitude:
		return m.AddedLongitude()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *HotelMutation) AddField(name string, value ent.Value) error {
	switch name {
	case hotel.FieldDestinationID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDestinationID(v)
		return nil
	case hotel.FieldLatitude:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddLatitude(v)
		return nil
	case hotel.FieldLongitude:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddLongitude(v)
		return nil
	}
	return fmt.Errorf("unknown Hotel numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *HotelMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(hotel.FieldLatitude) {
		fields = append(fields, hotel.FieldLatitude)
	}
	if m.FieldCleared(hotel.FieldLongitude) {
		fields = append(fields, hotel.FieldLongitude)
	}
	if m.FieldCleared(hotel.FieldCity) {
		fields = append(fields, hotel.FieldCity)
	}
	if m.FieldCleared(hotel.FieldCountry) {
		fields = append(fields, hotel.FieldCountry)
	}
	if m.FieldCleared(hotel.FieldPostalCode) {
		fields = append(fields, hotel.FieldPostalCode)
	}
	if m.FieldCleared(hotel.FieldDescription) {
		fields = append(fields, hotel.FieldDescription)
	}
	if m.FieldCleared(hotel.FieldAmenities) {
		fields = append(fields, hotel.FieldAmenities)
	}
	if m.FieldCleared(hotel.FieldImages) {
		fields = append(fields, hotel.FieldImages)
	}
	if m.FieldCleared(hotel.FieldBookingConditions) {
		fields = append(fields, hotel.FieldBookingConditions)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *HotelMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *HotelMutation) ClearField(name string) error {
	switch name {
	case hotel.FieldLatitude:
		m.ClearLatitude()
		return nil
	case hotel.FieldLongitude:
		m.ClearLongitude()
		return nil
	case hotel.FieldCity:
		m.ClearCity()
		return nil
	case hotel.FieldCountry:
		m.ClearCountry()
		return nil
	case hotel.FieldPostalCode:
		m.ClearPostalCode()
		return nil
	case hotel.FieldDescription:
		m.ClearDescription()
		return nil
	case hotel.FieldAmenities:
		m.ClearAmenities()
		return nil
	case hotel.FieldImages:
		m.ClearImages()
		return nil
	case hotel.FieldBookingConditions:
		m.ClearBookingConditions()
		return nil
	}
	return fmt.Errorf("unknown Hotel nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *HotelMutation) ResetField(name string) error {
	switch name {
	case hotel.FieldDestinationID:
		m.ResetDestinationID()
		return nil
	case hotel.FieldName:
		m.ResetName()
		return nil
	case hotel.FieldLatitude:
		m.ResetLatitude()
		return nil
	case hotel.FieldLongitude:
		m.ResetLongitude()
		return nil
	case hotel.FieldAddress:
		m.ResetAddress()
		return nil
	case hotel.FieldCity:
		m.ResetCity()
		return nil
	case hotel.FieldCountry:
		m.ResetCountry()
		return nil
	case hotel.FieldPostalCode:
		m.ResetPostalCode()
		return nil
	case hotel.FieldDescription:
		m.ResetDescription()
		return nil
	case hotel.FieldAmenities:
		m.ResetAmenities()
		return nil
	case hotel.FieldImages:
		m.ResetImages()
		return nil
	case hotel.FieldBookingConditions:
		m.ResetBookingConditions()
		return nil
	case hotel.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Hotel field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *HotelMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *HotelMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *HotelMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *HotelMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *HotelMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *HotelMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *HotelMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Hotel unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *HotelMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Hotel edge %s", name)
}
