// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/choonhong/hotel-data-merge/ent/hotel"
	"github.com/choonhong/hotel-data-merge/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	hotelFields := schema.Hotel{}.Fields()
	_ = hotelFields
	// hotelDescUpdatedAt is the schema descriptor for updated_at field.
	hotelDescUpdatedAt := hotelFields[13].Descriptor()
	// hotel.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	hotel.DefaultUpdatedAt = hotelDescUpdatedAt.Default.(func() time.Time)
}
