// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Data is the predicate function for data builders.
type Data func(*sql.Selector)

// Hotel is the predicate function for hotel builders.
type Hotel func(*sql.Selector)
